### ISSUE TITLE
Training on multiple GPUs

### ISSUE THREAD

**Issue by sorenwacker** [mpcrlab/MolecularTransformerEmbeddings#4]
I can run the training with the `--cpu` argument. And also when using a single GPU:

    CUDA_VISIBLE_DEVICES=0 python3 train.py --data_path=data/smiles_iupac_train_1k.tsv

However, when I make both GPUs visible to CUDA I get this error:

```
python3 train.py --data_path=data/smiles_iupac_train_1k.tsv 
Namespace(batch_size=24, checkpoint_path=None, cpu=False, data_path='data/smiles_iupac_train_1k.tsv', embedding_size=512, learning_rate=0.0001, max_length=256, num_epochs=10, num_layers=6)
2 GPUs available. Training with cuda.
Loaded 1000 samples from data/smiles_iupac_train_1k.tsv
Initializing Transformer...
Transformer Initialized on device(s): cuda
Starting epoch 1
0.0 minutes : epoch 1 : batch 1 : loss = 4.703032970428467
0.0 minutes : epoch 1 : batch 2 : loss = 4.682058334350586
Traceback (most recent call last):
  File "train.py", line 110, in <module>
    train_epoch(i, model, dataloader, optimizer, sched)
  File "train.py", line 63, in train_epoch
    loss.backward()
  File "/home/swacker/miniconda3/lib/python3.7/site-packages/torch/tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/swacker/miniconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 127, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: transform: failed to synchronize: cudaErrorAssert: device-side assert triggered`
```
Did you ever encounter this before?

**Comment by ptmorris03** [comment]
I haven't run into this error, but found it in one other place (with no answer) https://discuss.pytorch.org/t/bert-got-error-of-device-side-assert-tirggerred/68695

I've definitely run this code on 2 GPUs before, so I'll take a look at what CUDA/pytorch versions and CUDA driver were used and follow up with a docker container that's confirmed to work for multi-gpu.
