### ISSUE TITLE
How to use gpu for Embed.py ?

### ISSUE THREAD

**Issue by JinyuanSun** [mpcrlab/MolecularTransformerEmbeddings#6]
Hi, I try to use gpu for embedding and I modified the `embed.py` as follow:
```python
print("Loading pretrained weights from", args.checkpoint_path)
checkpoint = torch.load(args.checkpoint_path, map_location=torch.device("cuda"))
model.load_state_dict(checkpoint['state_dict'])
print("Pretrained weights loaded")
model = model.module.cpu()
encoder = model.encoder.cpu()
```
and 
```python
model = model.module.cuda()
encoder = model.encoder.cuda()
```
leads to:
```bash
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking arugment for argument index in method wrapper_index_select)
```
This way seems did not work out... Can anyone help me with it?

**Comment by ptmorris03** [comment]
Hello,

What error are you receiving, and does it only occur when using the GPU?

**Comment by JinyuanSun** [comment]
Hi,
I did not run into any error when using `embed.py` in this repo.  What I am looking for is to modify `embed.py` and to use GPU. I tried to change the `torch.device("cpu")` to `torch.device("cuda")` , but this did not work. After I change
```python
model = model.module.cpu()
encoder = model.encoder.cpu()
```
to
```python
model = model.module.cuda()
encoder = model.encoder.cuda()
```
The errors are:
```bash
Traceback (most recent call last):
  File "/home/af2/PLFormer/MolecularTransformerEmbeddings/embed.py", line 54, in <module>
    embedding = encoder(encoded, mask)[0].numpy()
  File "/home/af2/miniconda3/envs/torch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/af2/PLFormer/MolecularTransformerEmbeddings/transformer.py", line 206, in forward
    x = self.embed(src)
  File "/home/af2/miniconda3/envs/torch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/af2/PLFormer/MolecularTransformerEmbeddings/transformer.py", line 26, in forward
    return self.embed(x)
  File "/home/af2/miniconda3/envs/torch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/af2/miniconda3/envs/torch/lib/python3.9/site-packages/torch/nn/modules/sparse.py", line 158, in forward
    return F.embedding(
  File "/home/af2/miniconda3/envs/torch/lib/python3.9/site-packages/torch/nn/functional.py", line 2043, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking arugment for argument index in method wrapper_index_select)
```
Thanks a lot!

**Comment by ptmorris03** [comment]
Since you have moved the model weights to cuda, any input tensors (such as the ‘encoded’ and ‘mask’ variables passed to the model’s encoder on line 54 of embed.py) also need to be moved to the GPU with variable = variable.cuda() before they can be passed to the model. Information about PyTorch-related error messages like this one can be found at https://discuss.pytorch.org/

**Comment by JinyuanSun** [comment]
Thanks!
